FROM node:lts-buster

WORKDIR /usr/src/app

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

RUN npm install

COPY . .

ENV DB_USER=recipe_user DB_HOST=recipes_db RECIPE_DB=recipes_db DB_PASSWORD=user DB_PORT=5432 PORT=3001

EXPOSE 3001

CMD ["node", "retrieve_recipe.js"]