FROM node:latest

WORKDIR /usr/src/app

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

RUN npm install

COPY . .

ENV REACT_APP_POST_RECIPE_URL=http://localhost/postrecipe 
ENV REACT_APP_GET_RECIPE_URL=http://localhost/getrecipe

EXPOSE 3000


CMD ["npm", "start"]