FROM node:latest

WORKDIR /usr/src/app

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

RUN npm install

COPY . .

ENV REACT_APP_POST_RECIPE_URL=http://postrecipe:3002/recipe REACT_APP_GET_RECIPE_URL=http://getrecipe:3001/recipes

EXPOSE 3000


CMD ["npm", "start"]