apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-server
  template:
    metadata:
      labels:
        app: frontend-server
    spec:
      containers:
      - name: frontend
        image: skanderlahbaiel/frontend:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: frontend-config
