apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  REACT_APP_POST_RECIPE_URL: "http://myapp/postrecipe"
  REACT_APP_GET_RECIPE_URL: "http://myapp/getrecipe"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-server
  template:
    metadata:
      labels:
        app: frontend-server
    spec:
      containers:
      - name: frontend
        image: skanderlahbaiel/frontend:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

