apiVersion: apps/v1
kind: Deployment
metadata:
  name: getrecipe-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: getrecipe-server
  template:
    metadata:
      labels:
        app: getrecipe-server
    spec:
      containers:
      - name: getrecipe
        image: skanderlahbaiel/getrecipe:latest
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: postgres-service
---
apiVersion: v1
kind: Service
metadata:
  name: getrecipe-service
spec:
  selector:
    app: getrecipe-server
  ports:
    - protocol: TCP
      port: 3001  
      targetPort: 3001
  type: ClusterIP
