apiVersion: apps/v1
kind: Deployment
metadata:
  name: postrecipe-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postrecipe-server
  template:
    metadata:
      labels:
        app: postrecipe-server
    spec:
      containers:
      - name: postrecipe
        image: skanderlahbaiel/postrecipe:latest
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: postrecipe-service
spec:
  selector:
    app: postrecipe-server
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
