apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: default
spec:
  rules:
    - http:
        paths:
        - pathType: Prefix
          path: "/getrecipe"
          backend:
            service:
              name: getrecipe-service
              port:
                number: 81
        - pathType: Prefix
          path: "/postrecipe"
          backend:
            service:
              name: postrecipe-service
              port:
                number: 82
        - pathType: Prefix
          path: "/frontend"
          backend:
            service:
              name: frontend-service
              port:
                number: 80
